# Generated by Django 6.0.7 on 2026-08-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://img.favpng.com/6/11/15/food-logo-cutlery-and-plate-icon-for-dining-kgzBem0K_t.jpg', max_length=500),
        ),
    ]
